### ISSUE TITLE
Can not access repo

### ISSUE THREAD

**Issue by ZorianaPro** [haensl/react-redux-session#1]
Hey HP, I didn't know where write write :) 
So I can not push to this repo, access denied, could u make it accessable? 
Thank youuuu
![image](https://user-images.githubusercontent.com/26874704/79056046-a4119680-7c52-11ea-9b69-df3047dbe1a4.png)

**Comment by haensl** [comment]
Hi Zozo,

what exact command did you use to clone? You can only clone via `ssh` if your key is registered. What you need to do is: clone via `https`.

**Comment by haensl** [comment]
![Screenshot 2020-04-15 at 11 13 06](https://user-images.githubusercontent.com/12875760/79605676-a1022480-80f0-11ea-9780-6c2677d79cf8.png)

**Comment by haensl** [comment]
<img width="433" alt="Screenshot 2020-04-17 at 21 14 44" src="https://user-images.githubusercontent.com/12875760/79605701-afe8d700-80f0-11ea-8161-0f3d421bead7.png">
